version: "3"

services:
  db:
    image: mysql
    container_name: main.mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "django"
      MYSQL_USER: "django"
      MYSQL_PASSWORD: "django"
      TZ: "Asia/Seoul"
    ports:
        - "3307:3306"
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - 8083:8083
      - 3000:3000
    depends_on: 
      - db
    command: bash -c "python ./worktime_project/manage.py runserver 0.0.0.0:8083"